import type { Address, AddressSuggestion } from '../domain/location.types';

export const fakeAddresses: Address[] = [
  {
    id: 'address-paseo-65',
    formatted: 'Paseo Marítimo Rey de España, 65, 29640 Fuengirola, Málaga',
    street: 'Paseo Marítimo Rey de España',
    houseNumber: '65',
    unit: null,
    buildingName: null,
    floor: null,
    door: null,
    postalCode: '29640',
    locality: 'Fuengirola',
    municipality: 'Fuengirola',
    province: 'Málaga',
    countryCode: 'ES',
    kind: 'residential',
    meetingPoint: null,
    instructions: null,
    coordinates: {
      latitude: 36.5384,
      longitude: -4.6239,
      accuracyMeters: 20,
      capturedAt: '2026-07-31T00:00:00.000Z',
      source: 'address_search',
    },
    providerReference: 'fake:serviceable:paseo-65',
  },
  {
    id: 'address-hotel',
    formatted: 'Hotel Las Palmeras, Calle Martínez Catena, 6, 29640 Fuengirola, Málaga',
    street: 'Calle Martínez Catena',
    houseNumber: '6',
    unit: null,
    buildingName: 'Hotel Las Palmeras',
    floor: null,
    door: null,
    postalCode: '29640',
    locality: 'Fuengirola',
    municipality: 'Fuengirola',
    province: 'Málaga',
    countryCode: 'ES',
    kind: 'hotel',
    meetingPoint: 'Recepción principal',
    instructions: null,
    coordinates: {
      latitude: 36.5398,
      longitude: -4.6254,
      accuracyMeters: 18,
      capturedAt: '2026-07-31T00:00:00.000Z',
      source: 'address_search',
    },
    providerReference: 'fake:serviceable:hotel',
  },
  {
    id: 'address-condominium',
    formatted: 'Residencial Mediterráneo, Avenida de Carvajal, 45, 29640 Fuengirola, Málaga',
    street: 'Avenida de Carvajal',
    houseNumber: '45',
    unit: 'Portal B',
    buildingName: 'Residencial Mediterráneo',
    floor: null,
    door: null,
    postalCode: '29640',
    locality: 'Fuengirola',
    municipality: 'Fuengirola',
    province: 'Málaga',
    countryCode: 'ES',
    kind: 'condominium',
    meetingPoint: 'Entrada principal',
    instructions: null,
    coordinates: {
      latitude: 36.5672,
      longitude: -4.5998,
      accuracyMeters: 22,
      capturedAt: '2026-07-31T00:00:00.000Z',
      source: 'address_search',
    },
    providerReference: 'fake:serviceable:condominium',
  },
  {
    id: 'address-outside',
    formatted: 'Avenida Ricardo Soriano, 20, 29601 Marbella, Málaga',
    street: 'Avenida Ricardo Soriano',
    houseNumber: '20',
    unit: null,
    buildingName: null,
    floor: null,
    door: null,
    postalCode: '29601',
    locality: 'Marbella',
    municipality: 'Marbella',
    province: 'Málaga',
    countryCode: 'ES',
    kind: 'business',
    meetingPoint: null,
    instructions: null,
    coordinates: {
      latitude: 36.5101,
      longitude: -4.8855,
      accuracyMeters: 15,
      capturedAt: '2026-07-31T00:00:00.000Z',
      source: 'address_search',
    },
    providerReference: 'fake:out-of-area:marbella',
  },
];

export const fakeSuggestions: AddressSuggestion[] = fakeAddresses.map((address) => ({
  id: address.id ?? address.providerReference ?? address.formatted,
  label: address.buildingName || `${address.street ?? address.formatted}${address.houseNumber ? `, ${address.houseNumber}` : ''}`,
  secondaryLabel: `${address.postalCode ?? ''} ${address.locality}`.trim(),
  kind: address.kind,
  providerReference: address.providerReference ?? address.formatted,
}));
